DB:
    DbPath:  /var/www/html/Data/SpaceTraders.db
    DbBuild: /var/www/html/Data/BuildSqlite.sql
    DbReset: /var/www/html/Data/ResetSqlite.sql
LOG:
    ErrPath: /var/www/html/Logs/Go_Error.log
    ActPath: /var/www/html/Logs/Go_Activity.log
API:
    AgentName: NULLSKY
    AgentFaction: VOID
    AccntToken: 
    AgentToken: 
